# Generated by Django 3.1 on 2020-09-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=255)),
                ('start_year', models.IntegerField()),
                ('intake', models.IntegerField()),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
