# Generated by Django 3.1 on 2020-09-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0005_visiting_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facillities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
