# Generated by Django 3.1 on 2020-10-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0009_auto_20201002_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mobile_number',
            field=models.CharField(max_length=255),
        ),
    ]
